services:
  mongo:
    image: mongo:8
    container_name: az-group-sync-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: azuresyncdb
    networks:
      - az-group-sync-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: az-group-sync-api
    image: az-group-sync:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - TZ=Asia/Singapore
      - COMPOSE_BAKE=true
    env_file:
      - .env
    networks:
      - az-group-sync-network

  mongo-express:
    image: mongo-express:latest
    container_name: az-group-sync-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_WEB_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_WEB_PASSWORD:-pass}
    networks:
      - az-group-sync-network

networks:
  az-group-sync-network:
    driver: bridge
    name: az-group-sync-network

volumes:
  mongo-data:
